name: test

on:
  push:
    branches:
    tags:
    paths:
      - '.github/workflows/test.yml'
      - '*.go'
      - '.golangci.yml'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '*.go'
      - '.golangci.yml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: tests
        run: |
          export TZ="Asia/Novosibirsk"
          date
          go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...

      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.20.0
          go get -u github.com/mattn/goveralls

      - name: run backend linters
        run: $GITHUB_WORKSPACE/golangci-lint run --config .golangci.yml ./...

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

